db.vehiculos.insertMany([
    {coche:"Seat",modelo:"Ibiza",color:"Blanco",Garaje:"Aeropuerto"},
    {coche:"Audi",modelo:"A3",color:"Gris",Garaje:"Estacion de trenes"},
    {coche:"Opel",modelo:"Astra",color:"Negro",Garaje:"Aeropuerto"},
    {coche:"Ford",modelo:"Focus",color:"Azul",Garaje:"Estacion de trenes"},
    {coche:"BMW",modelo:"Serie3",color:"Rojo",Garaje:"Aeropuerto"},
    {coche:"Peugeot",modelo:"2008",color:"Amarillo",Garaje:"Aeropuerto"},
    {coche:"Citroen",modelo:"C4",color:"Verde",Garaje:"Estacion de trenes"},
    {coche:"Opel",modelo:"Corsa",color:"Rojo",Garaje:"Aeropuerto"},
    {coche:"Ford",modelo:"Focus",color:"Gris",Garaje:"Estacion de trenes"},
    {coche:"Peugeot",modelo:"3008",color:"Amarillo",Garaje:"Aeropuerto"},
    {coche:"BMW",modelo:"Serie5",color:"Negro",Garaje:"Estacion de trenes"},
    {coche:"Seat",modelo:"Leon",color:"Gris",Garaje:"Aeropuerto"},
    {coche:"Audi",modelo:"A3",color:"Rojo",Garaje:"Aeropuerto"},
    {coche:"BMW",modelo:"Serie3",color:"Verde",Garaje:"Estacion de trenes"},
    {coche:"Audi",modelo:"A5",color:"Gris",Garaje:"Estacion de trenes"},
    {coche:"Citroen",modelo:"C3",color:"Blanco",Garaje:"Aeropuerto"},
    {coche:"Seat",modelo:"Leon",color:"Azul",Garaje:"Estacion de trenes"},
    {coche:"Peugeot",modelo:"208",color:"Blanco",Garaje:"Aeropuerto"},
    {coche:"Citroen",modelo:"C4",color:"Rojo",Garaje:"Estacion de trenes"},
    {coche:"Ford",modelo:"Fiesta",color:"Negro",Garaje:"Aeropuerto"},
])